spring.application.name=eCommerceSpringBackend
server.port=8080
spring.datasource.url=jdbc:oracle:thin:@dinkdb_medium?TNS_ADMIN=C:/SQLDEV/02_program/Wallet_DinkDB
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=DA2602
spring.datasource.password=Data2602